<a href="https://colab.research.google.com/github/q0015300153/school_AI_and_security/blob/master/20200314_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [1]:
import numpy as np
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [6]:
import numpy as np
np.indices((3, 3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [5]:
import numpy as np
ar10=np.diag((2,1,4,6));
ar10

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

In [4]:
import numpy as np
a = np.array([0, 1, 2])
np.tile(a, 2)

array([0, 1, 2, 0, 1, 2])

In [3]:
import numpy as np
a = np.array([0, 1, 2])
np.tile(a, (2, 2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [2]:
import numpy as np
a = np.array([0, 1, 2])
np.tile(a, (2, 1, 2))

array([[[0, 1, 2, 0, 1, 2]],

       [[0, 1, 2, 0, 1, 2]]])

In [8]:
import csv
import numpy as np

x = '''1,3,2,3,1,2,3,4
2,4,5,0.6,5,6,7,8
3,7,8,9,9,10,11,12
4,1,1.1,1.2,13,14,15,16
'''
with open("abc.txt",mode="w",encoding="utf-8") as file:
  file.write(x)
file.close()

np.genfromtxt('abc.txt', delimiter=',', invalid_raise = False)

array([[ 1. ,  3. ,  2. ,  3. ,  1. ,  2. ,  3. ,  4. ],
       [ 2. ,  4. ,  5. ,  0.6,  5. ,  6. ,  7. ,  8. ],
       [ 3. ,  7. ,  8. ,  9. ,  9. , 10. , 11. , 12. ],
       [ 4. ,  1. ,  1.1,  1.2, 13. , 14. , 15. , 16. ]])

In [7]:
import numpy as np
np.tile(np.array([[1,2],[6,7]]),3)

array([[1, 2, 1, 2, 1, 2],
       [6, 7, 6, 7, 6, 7]])

In [9]:
import numpy as np
np.tile(np.array([[1,2],[6,7]]),(2,2))

array([[1, 2, 1, 2],
       [6, 7, 6, 7],
       [1, 2, 1, 2],
       [6, 7, 6, 7]])

In [10]:
import numpy as np
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [11]:
import numpy as np
np.tile(np.array([[1,2],[6,7]]),3)

array([[1, 2, 1, 2, 1, 2],
       [6, 7, 6, 7, 6, 7]])

In [12]:
import numpy as np
np.tile(np.array([[1,2],[6,7]]),(2,2))

array([[1, 2, 1, 2],
       [6, 7, 6, 7],
       [1, 2, 1, 2],
       [6, 7, 6, 7]])

In [13]:
import numpy as np
x = np.arange(2,10).reshape(2,4)
x

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [14]:
import numpy as np
y = np.arange(2,10).reshape(4,2)
y

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [15]:
import numpy as np
ar=np.array([np.arange(1,6),np.arange(10,15)]);
ar

array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14]])

In [16]:
import numpy as np
ar=np.array([np.arange(1,6),np.arange(10,15)])
ar.ravel()

array([ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14])

In [17]:
import numpy as np
ar=np.array([np.arange(1,6),np.arange(10,15)])
ar.T

array([[ 1, 10],
       [ 2, 11],
       [ 3, 12],
       [ 4, 13],
       [ 5, 14]])

In [18]:
import numpy as np
ar=ar[:, np.newaxis]; ar.shape
ar

array([[[ 1,  2,  3,  4,  5]],

       [[10, 11, 12, 13, 14]]])

In [19]:
import numpy as np
ar=np.array([np.arange(1,6),np.arange(10,15)])
ar.T.ravel()

array([ 1, 10,  2, 11,  3, 12,  4, 13,  5, 14])

In [20]:
import numpy as np
ar=np.array([14,15,16])
ar=ar[:, np.newaxis]
ar.shape

(3, 1)

In [21]:
import numpy as np
x = np.arange(2,10)
# x
print(x[0])
print(x[-2])
print(x[-1])

2
8
9


In [22]:
import numpy as np
ar = np.array([[2,3,4],[9,8,7],[11,12,13]])
ar[1,2]

7

In [23]:
import numpy as np
ar=2*np.arange(6)
# ar
ar[1:5:2]

array([2, 6])

In [24]:
import numpy as np
ar=2*np.arange(6)
# ar
ar[1:6:2]

array([ 2,  6, 10])

In [25]:
import numpy as np
ar=2*np.arange(6)
# ar
ar[:4]

array([0, 2, 4, 6])

In [26]:
import numpy as np
ar = np.array([[2,3,4],[9,8,7],[11,12,13]])
# ar
ar[2,:]

array([11, 12, 13])

In [27]:
import numpy as np
ar = np.array([[2,3,4],[9,8,7],[11,12,13]])
# ar
ar[:,1]

array([ 3,  8, 12])

In [28]:
import numpy as np
ar = np.array([[2,3,4],[9,8,7],[11,12,13]])
# ar
ar[2,-1]

13

In [29]:
import numpy as np
ar=2*np.arange(6)
# ar
ar[::3]

array([0, 6])

In [30]:
import numpy as np
ar=2*np.arange(6)
# ar
ar[:3]=1
ar

array([ 1,  1,  1,  6,  8, 10])

In [31]:
import numpy as np
ar=2*np.arange(6)
# ar
ar[2:]=np.ones(4)
ar

array([0, 2, 1, 1, 1, 1])

In [32]:
import numpy as np
ar=np.arange(1,5)
ar.prod()

24

In [33]:
import numpy as np
ar=np.array([[2,3,4],[5,6,7],[8,9,10]])
ar.sum()

54

In [35]:
import numpy as np
ar=np.array([[2,3,4],[5,6,7],[8,9,10]])
ar.mean()

6.0

In [37]:
import numpy as np
ar=np.array([[2,3,4],[5,6,7],[8,9,10]])
np.median(ar)

6.0

In [38]:
ar=np.array([np.arange(1,6),np.arange(1,6)])
# ar
np.prod(ar,axis=0)

array([ 1,  4,  9, 16, 25])

In [39]:
ar=np.array([np.arange(1,6),np.arange(1,6)])
# ar
np.prod(ar,axis=1)

array([120, 120])

In [40]:
import numpy as np
arr = np.arange(10)
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [41]:
import numpy as np
arr = np.arange(10)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [42]:
import numpy as np
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
# arr
arr + arr

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [43]:
import numpy as np
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
# arr
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [44]:
import numpy as np
ar=np.array([[1,1],[1,1]])
ar2=np.array([[2,2],[2,2]])
ar * ar2

array([[2, 2],
       [2, 2]])

In [46]:
import numpy as np
ar=np.array([[1, 1], [1, 1]])
ar2=np.array([[2, 2], [2, 2]])
ar.dot(ar2)

array([[4, 4],
       [4, 4]])

In [48]:
import numpy as np
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
# arr
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
import numpy as np
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
# arr
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [50]:
import numpy as np
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
# arr
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [51]:
import numpy as np
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [52]:
import numpy as np
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [53]:
import numpy as np
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)
np.multiply(x1, x2)

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

In [54]:
import numpy as np
np.arange(3) + 5

array([5, 6, 7])

In [55]:
import numpy as np
np.ones((3, 3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [56]:
import numpy as np
np.arange(3).reshape((3, 1)) + np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [58]:
import numpy as np
np.random.randint(1,5)

3

In [59]:
import numpy as np
np.random.randint(-5,5,size=(2,2))

array([[ 3, -3],
       [-4,  3]])

In [60]:
import numpy as np
np.random.seed(0)
x1 = np.random.randint(10, size=6)
x1

array([5, 0, 3, 3, 7, 9])

In [61]:
import numpy as np
np.random.seed(0)
x2 = np.random.randint(10, size=(3, 4))
x2

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [62]:
import numpy as np
np.random.seed(0)
x3 = np.random.randint(10, size=(3, 4, 5))
x3

array([[[5, 0, 3, 3, 7],
        [9, 3, 5, 2, 4],
        [7, 6, 8, 8, 1],
        [6, 7, 7, 8, 1]],

       [[5, 9, 8, 9, 4],
        [3, 0, 3, 5, 0],
        [2, 3, 8, 1, 3],
        [3, 3, 7, 0, 1]],

       [[9, 9, 0, 4, 7],
        [3, 2, 7, 2, 0],
        [0, 4, 5, 5, 6],
        [8, 4, 1, 4, 9]]])

In [64]:
import numpy as np
np.random.randint(1, size=5)

array([0, 0, 0, 0, 0])

In [65]:
import numpy as np
np.convolve([1, 2, 3], [0, 1, 0.5])

array([0. , 1. , 2.5, 4. , 1.5])

In [66]:
import numpy as np
np.convolve([1,2,3],[0,1,0.5], 'same')

array([1. , 2.5, 4. ])

In [67]:
import numpy as np
np.convolve([1,2,3],[0,1,0.5], 'valid')

array([2.5])

In [68]:
import numpy as np
np.convolve([1, 2, 3], [0, 1, 0.5])

array([0. , 1. , 2.5, 4. , 1.5])

In [70]:
import numpy as np
ar = np.array([[3, 2], [10, -1]])
# ar
ar.sort(axis=1)
ar

array([[ 2,  3],
       [-1, 10]])

In [71]:
import numpy as np
ar=np.array([[3,2],[10,-1]])
# ar
ar.sort(axis=0)
ar

array([[ 3, -1],
       [10,  2]])

In [72]:
import numpy as np
ar=np.random.randint(10,size=5)
ar.sort()
ar[::-1]

array([9, 8, 7, 1, 1])